### PR TITLE
[spring-server] fix: Exclude stacktraces when null values are specified for non-null parameters

### LINKED ISSUE #423: graphql-kotlin-spring-server includes stacktraces in validation errors
**Library Version**
1.1.0

**Describe the bug**
`graphql-kotlin-spring-server` returns GraphQL validation error with stack trace for invalid requests specifying null values for non-null parameters.

**To Reproduce**
Start `graphql-kotlin-spring-example` app and run following query (without specifying any query variables)

```graphql
query echo($msg:String!) {
  forceLowercaseEcho(msg: $msg)
}
``` 

**Expected behavior**
GraphQL validation error returned without stack trace information.

Actual response:
```json
{
  "errors": [
    {
      "cause": null,
      "stackTrace": [
        {
          "methodName": "coerceArgumentValues",
          "fileName": "ValuesResolver.java",
          "lineNumber": 86,
          "className": "graphql.execution.ValuesResolver",
          "nativeMethod": false
        },
        {
          "methodName": "execute",
          "fileName": "Execution.java",
          "lineNumber": 71,
          "className": "graphql.execution.Execution",
          "nativeMethod": false
        },
        {
          "methodName": "execute",
          "fileName": "GraphQL.java",
          "lineNumber": 605,
          "className": "graphql.GraphQL",
          "nativeMethod": false
        },
        {
          "methodName": "parseValidateAndExecute",
          "fileName": "GraphQL.java",
          "lineNumber": 538,
          "className": "graphql.GraphQL",
          "nativeMethod": false
        },
        {
          "methodName": "executeAsync",
          "fileName": "GraphQL.java",
          "lineNumber": 502,
          "className": "graphql.GraphQL",
          "nativeMethod": false
        },
        {
          "methodName": "executeQuery$suspendImpl",
          "fileName": "QueryHandler.kt",
          "lineNumber": 54,
          "className": "com.expediagroup.graphql.spring.execution.SimpleQueryHandler",
          "nativeMethod": false
        },
        {
          "methodName": "executeQuery",
          "fileName": "QueryHandler.kt",
          "lineNumber": -1,
          "className": "com.expediagroup.graphql.spring.execution.SimpleQueryHandler",
          "nativeMethod": false
        },
        {
          "methodName": "invokeSuspend",
          "fileName": "RoutesConfiguration.kt",
          "lineNumber": 57,
          "className": "com.expediagroup.graphql.spring.RoutesConfiguration$graphQLRoutes$1$1",
          "nativeMethod": false
        },
        {
          "methodName": "resumeWith",
          "fileName": "ContinuationImpl.kt",
          "lineNumber": 33,
          "className": "kotlin.coroutines.jvm.internal.BaseContinuationImpl",
          "nativeMethod": false
        },
        {
          "methodName": "resumeMode",
          "fileName": "ResumeMode.kt",
          "lineNumber": 67,
          "className": "kotlinx.coroutines.ResumeModeKt",
          "nativeMethod": false
        },
        {
          "methodName": "resume",
          "fileName": "Dispatched.kt",
          "lineNumber": 319,
          "className": "kotlinx.coroutines.DispatchedKt",
          "nativeMethod": false
        },
        {
          "methodName": "resumeUnconfined",
          "fileName": "Dispatched.kt",
          "lineNumber": 49,
          "className": "kotlinx.coroutines.DispatchedKt",
          "nativeMethod": false
        },
        {
          "methodName": "dispatch",
          "fileName": "Dispatched.kt",
          "lineNumber": 298,
          "className": "kotlinx.coroutines.DispatchedKt",
          "nativeMethod": false
        },
        {
          "methodName": "dispatchResume",
          "fileName": "CancellableContinuationImpl.kt",
          "lineNumber": 250,
          "className": "kotlinx.coroutines.CancellableContinuationImpl",
          "nativeMethod": false
        },
        {
          "methodName": "resumeImpl",
          "fileName": "CancellableContinuationImpl.kt",
          "lineNumber": 260,
          "className": "kotlinx.coroutines.CancellableContinuationImpl",
          "nativeMethod": false
        },
        {
          "methodName": "resumeWith",
          "fileName": "CancellableContinuationImpl.kt",
          "lineNumber": 189,
          "className": "kotlinx.coroutines.CancellableContinuationImpl",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "Await.kt",
          "lineNumber": 143,
          "className": "kotlinx.coroutines.reactive.AwaitKt$awaitOne$$inlined$suspendCancellableCoroutine$lambda$1",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "StrictSubscriber.java",
          "lineNumber": 123,
          "className": "reactor.core.publisher.StrictSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "FluxContextStart.java",
          "lineNumber": 122,
          "className": "reactor.core.publisher.FluxContextStart$ContextStartSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "Operators.java",
          "lineNumber": 1820,
          "className": "reactor.core.publisher.Operators$MultiSubscriptionSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "Operators.java",
          "lineNumber": 1820,
          "className": "reactor.core.publisher.Operators$MultiSubscriptionSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "FluxMapFuseable.java",
          "lineNumber": 144,
          "className": "reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "FluxContextStart.java",
          "lineNumber": 122,
          "className": "reactor.core.publisher.FluxContextStart$ContextStartSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "FluxMapFuseable.java",
          "lineNumber": 336,
          "className": "reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "FluxFilterFuseable.java",
          "lineNumber": 384,
          "className": "reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "complete",
          "fileName": "Operators.java",
          "lineNumber": 1593,
          "className": "reactor.core.publisher.Operators$MonoSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "MonoCollectList.java",
          "lineNumber": 121,
          "className": "reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "FluxMap.java",
          "lineNumber": 136,
          "className": "reactor.core.publisher.FluxMap$MapSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "FluxPeek.java",
          "lineNumber": 252,
          "className": "reactor.core.publisher.FluxPeek$PeekSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onComplete",
          "fileName": "FluxMap.java",
          "lineNumber": 136,
          "className": "reactor.core.publisher.FluxMap$MapSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "terminateReceiver",
          "fileName": "FluxReceive.java",
          "lineNumber": 397,
          "className": "reactor.netty.channel.FluxReceive",
          "nativeMethod": false
        },
        {
          "methodName": "drainReceiver",
          "fileName": "FluxReceive.java",
          "lineNumber": 197,
          "className": "reactor.netty.channel.FluxReceive",
          "nativeMethod": false
        },
        {
          "methodName": "request",
          "fileName": "FluxReceive.java",
          "lineNumber": 108,
          "className": "reactor.netty.channel.FluxReceive",
          "nativeMethod": false
        },
        {
          "methodName": "request",
          "fileName": "FluxMap.java",
          "lineNumber": 155,
          "className": "reactor.core.publisher.FluxMap$MapSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "request",
          "fileName": "FluxPeek.java",
          "lineNumber": 130,
          "className": "reactor.core.publisher.FluxPeek$PeekSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "request",
          "fileName": "FluxMap.java",
          "lineNumber": 155,
          "className": "reactor.core.publisher.FluxMap$MapSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onSubscribe",
          "fileName": "MonoCollectList.java",
          "lineNumber": 72,
          "className": "reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onSubscribe",
          "fileName": "FluxMap.java",
          "lineNumber": 86,
          "className": "reactor.core.publisher.FluxMap$MapSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onSubscribe",
          "fileName": "FluxPeek.java",
          "lineNumber": 163,
          "className": "reactor.core.publisher.FluxPeek$PeekSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "onSubscribe",
          "fileName": "FluxMap.java",
          "lineNumber": 86,
          "className": "reactor.core.publisher.FluxMap$MapSubscriber",
          "nativeMethod": false
        },
        {
          "methodName": "startReceiver",
          "fileName": "FluxReceive.java",
          "lineNumber": 276,
          "className": "reactor.netty.channel.FluxReceive",
          "nativeMethod": false
        },
        {
          "methodName": "lambda$subscribe$2",
          "fileName": "FluxReceive.java",
          "lineNumber": 125,
          "className": "reactor.netty.channel.FluxReceive",
          "nativeMethod": false
        },
        {
          "methodName": "safeExecute",
          "fileName": "AbstractEventExecutor.java",
          "lineNumber": 163,
          "className": "io.netty.util.concurrent.AbstractEventExecutor",
          "nativeMethod": false
        },
        {
          "methodName": "runAllTasks",
          "fileName": "SingleThreadEventExecutor.java",
          "lineNumber": 416,
          "className": "io.netty.util.concurrent.SingleThreadEventExecutor",
          "nativeMethod": false
        },
        {
          "methodName": "run",
          "fileName": "NioEventLoop.java",
          "lineNumber": 515,
          "className": "io.netty.channel.nio.NioEventLoop",
          "nativeMethod": false
        },
        {
          "methodName": "run",
          "fileName": "SingleThreadEventExecutor.java",
          "lineNumber": 918,
          "className": "io.netty.util.concurrent.SingleThreadEventExecutor$5",
          "nativeMethod": false
        },
        {
          "methodName": "run",
          "fileName": "ThreadExecutorMap.java",
          "lineNumber": 74,
          "className": "io.netty.util.internal.ThreadExecutorMap$2",
          "nativeMethod": false
        },
        {
          "methodName": "run",
          "fileName": "FastThreadLocalRunnable.java",
          "lineNumber": 30,
          "className": "io.netty.util.concurrent.FastThreadLocalRunnable",
          "nativeMethod": false
        },
        {
          "methodName": "run",
          "fileName": "Thread.java",
          "lineNumber": 748,
          "className": "java.lang.Thread",
          "nativeMethod": false
        }
      ],
      "locations": [
        {
          "line": 1,
          "column": 12,
          "sourceName": null
        }
      ],
      "errorType": "ValidationError",
      "message": "Variable 'msg' has coerced Null value for NonNull type 'String!'",
      "path": null,
      "extensions": null,
      "localizedMessage": "Variable 'msg' has coerced Null value for NonNull type 'String!'",
      "suppressed": []
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by tk26**
📝 Description
Refer https://github.com/ExpediaGroup/graphql-kotlin/issues/423#issuecomment-539622384 for the cause
The fix includes setting `stackTrace` to an empty array when the error type is a `ValidationError` and a `NonNullableValueCoercedAsNullException` was thrown

🔗 Related Issues
Resolves #423

### CODE REVIEW

File: graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt [hunk 1]
```diff
@@ -29,6 +31,12 @@ data class GraphQLResponse(
 )
 
 fun ExecutionResult.toGraphQLResponse(): GraphQLResponse {
+    errors?.forEach {
```
Comment (dariuszkuc) [inline graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt]: While this indeed fixes the issue, it is very specific to that single case and if another GraphQL error is returned that is also an Exception we will be returning stacktraces as well.

Let's change it to more generic
```
val filteredErrors = if (errors?.isNotEmpty() == true) {
    errors.map {
        when (it) {
            is SimpleKotlinGraphQLError -> it
            is Exception -> SimpleKotlinGraphQLError(exception = it, locations = it.locations, path = it.path, errorType = it.errorType)
            else -> it
        }
    }
} else {
    null
}
```

Comment (smyrick) [reply graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt]: +1, let's make this more generic

Comment (tk26) [reply graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt]: Good call. Made the change. @dariuszkuc @smyrick

File: graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt [hunk 2]
```diff
@@ -29,7 +31,14 @@ data class GraphQLResponse(
 )
 
 fun ExecutionResult.toGraphQLResponse(): GraphQLResponse {
-    val filteredErrors = if (errors?.isNotEmpty() == true) errors else null
+    val filteredErrors = if (errors?.isNotEmpty() == true) {
+        errors.map {
+            when (it) {
+                is Exception -> SimpleKotlinGraphQLError(exception = it, locations = it.locations, path = it.path, errorType = it.errorType)
```
Comment (dariuszkuc) [inline graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt]: logic here should be 

1) if it is an instance of `SimpleKotlinGraphQLError` then just return it
2) if it is an Exception then wrap it in `SimpleKotlinGraphQLError
3) otherwise just return the GraphQLError

You need to add the first case as you could implement `SimpleKotlinGraphQLError` that is also an Exception and we don't want to wrap it twice

Comment (tk26) [reply graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt]: Wow, yeah. Done :)

**Comment by tk26** [comment]
> Actually can we add one more test case for the default behavior

@smyrick I think we do have one already for the default behavior - https://github.com/ExpediaGroup/graphql-kotlin/blob/master/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponseKtTest.kt#L75
